[package]
name = "git-housekeeping"
version = "0.1.0"
authors = ["Bradford D. Boyle <bboyle@pivotal.io>"]

[dependencies]
chrono = "0.3"
csv = "1.0"
failure = "0.1"
git2 = "0.7"
graphql_client = "0.5"
reqwest = "0.9"
structopt = "0.2"
serde = "1.0"
serde_derive = "1.0"
