resources:
- name: git-housekeeping
  type: git
  source:
    uri: https://github.com/bradfordboyle/git-housekeeping.git
- name: timer
  type: time
  source:
    start: 8:00 AM
    stop: 6:00 PM
    interval: 5m
    location: America/Los_Angeles

- name: apache-geode
  type: git
  source:
    uri: https://github.com/apache/geode.git

jobs:
- name: check-apache-geode
  plan:
  - aggregate:
    - get: timer
      trigger: true
    - get: git-housekeeping
    - get: apache-geode
  - task: check-apache-geode
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: rust
          tag: 1.29-stretch
      run:
        path: sh
        args:
        - -ec
        - |
          cargo --quiet install xsv
          cd apache-geode
          git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
          git fetch --quiet
          git for-each-ref refs/remotes/origin --format='"%(committerdate:iso8601)","%(authorname)","%(refname:short)"' | xsv sort -n -s1 | xsv table

      inputs:
      - name: apache-geode
